address: 127.0.0.1:8888

telemetry:
  log:
    level: debug

#ingest:
#  kafka:
#    # To enable stats reporting set this value to >=5s.
#    # Setting this value to 0 makes reporting explicitly disabled.
#    statsInterval: 5s
#    # Set IP address family used for communicating with Kafka cluster
#    brokerAddressFamily: v4
#    # Use this configuration parameter to define how frequently the local metadata cache needs to be updated.
#    # It cannot be lower than 10 seconds.
#    topicMetadataRefreshInterval: 1m
#    # Use this config parameter to enable TCP keep-alive in order to prevent the Kafka broker to close idle network connection.
#    socketKeepAliveEnabled: true
#    # Set list of debug contexts to enable for librdkafka
#    # See: https://github.com/confluentinc/librdkafka/blob/master/INTRODUCTION.md#debug-contexts
#    debugContexts:
#      - broker
#      - topic

# dedupe:
#   enabled: true
#   driver: redis
#   config:
#     address: 127.0.0.1:6379
#     database: 0
#     expiration: 768h # 32d

# Entitlements
entitlements:
  enabled: true

# System event generation
events:
  enabled: false
# systemEvents:
#   enabled: true
#   topic: om_sys.api_events
#   autoProvision:
#     enabled: true
#     partitions: 4
# ingestEvents:
#   enabled: true
#   topic: om_sys.ingest_events
#   autoProvision:
#     enabled: true
#     partitions: 8

# Consumer portal
# portal:
#   enabled: true
#   tokenSecret: this-isnt-secure

postgres:
  url: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
  autoMigrate: true # Runs migrations as part of the service startup

meters:
  # Sample meter to count API requests
  - slug: api_requests_total        # Unique identifier for the meter
    description: API Requests
    eventType: request              # Filter events by type
    aggregation: COUNT              # Aggregation method: COUNT, SUM, etc.
    groupBy:
      method: $.method              # HTTP Method: GET, POST, etc.
      route: $.route                # Route: /products/:product_id

  # Sample meter to count LLM Token Usage
  - slug: tokens_total
    description: AI Token Usage
    eventType: prompt               # Filter events by type
    aggregation: SUM
    valueProperty: $.tokens         # JSONPath to parse usage value
    groupBy:
      model: $.model                # AI model used: gpt4-turbo, etc.
      type: $.type                  # Prompt type: input, output, system
